In [53]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/gender-by-name/name_gender_dataset.csv

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [3]:
import pandas as pd

# This path is created automatically by Kaggle when you add the dataset
df = pd.read_csv("/kaggle/input/gender-by-name/name_gender_dataset.csv")

# Display the first few rows
df.head()

      Name Gender    Count  Probability
0    James      M  5304407     0.014517
1     John      M  5260831     0.014398
2   Robert      M  4970386     0.013603
3  Michael      M  4579950     0.012534
4  William      M  4226608     0.011567

In [4]:
df.isna().sum()

Name           0
Gender         0
Count          0
Probability    0
dtype: int64

In [6]:
df.Name = df.Name.str.lower()

In [8]:
df

           Name Gender    Count   Probability
0         james      M  5304407  1.451679e-02
1          john      M  5260831  1.439753e-02
2        robert      M  4970386  1.360266e-02
3       michael      M  4579950  1.253414e-02
4       william      M  4226608  1.156713e-02
...         ...    ...      ...           ...
147264   zylenn      M        1  2.736740e-09
147265   zymeon      M        1  2.736740e-09
147266   zyndel      M        1  2.736740e-09
147267   zyshan      M        1  2.736740e-09
147268    zyton      M        1  2.736740e-09

[147269 rows x 4 columns]

In [10]:
df["label"] = df["Gender"].map({"M" : 1, "F" : 0 })

In [12]:
df

           Name Gender    Count   Probability  label
0         james      M  5304407  1.451679e-02      1
1          john      M  5260831  1.439753e-02      1
2        robert      M  4970386  1.360266e-02      1
3       michael      M  4579950  1.253414e-02      1
4       william      M  4226608  1.156713e-02      1
...         ...    ...      ...           ...    ...
147264   zylenn      M        1  2.736740e-09      1
147265   zymeon      M        1  2.736740e-09      1
147266   zyndel      M        1  2.736740e-09      1
147267   zyshan      M        1  2.736740e-09      1
147268    zyton      M        1  2.736740e-09      1

[147269 rows x 5 columns]

In [14]:
vectorizer = CountVectorizer(analyzer='char', ngram_range=(2, 4))
X = vectorizer.fit_transform(df["Name"])
y = df["label"]

# from sklearn.ensemble import RandomForestClassifier

# model = RandomForestClassifier()
# model.fit(X_train, y_train)

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2,stratify = y, random_state=42
)

In [19]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [20]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.7341617437359951

Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.77      0.78     17950
           1       0.65      0.68      0.67     11504

    accuracy                           0.73     29454
   macro avg       0.72      0.72      0.72     29454
weighted avg       0.74      0.73      0.74     29454

In [21]:
# Step 8: Test Your Own Names
def predict_gender(name):
    name = [name.lower()]
    name_vec = vectorizer.transform(name)
    pred = model.predict(name_vec)[0]
    return "Male" if pred == 1 else "Female"

# Try it out!
print(predict_gender("yusha"))
print(predict_gender("Sophia"))
print(predict_gender("Zaid"))
print(predict_gender("Ritika"))

Male
Female
Male
Female

Gender
F    89749
M    57520
Name: count, dtype: int64